apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taiga-ingress
  namespace: taiga
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taiga-front
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: taiga-back
                port:
                  number: 8000
          - path: /openid/
            pathType: Prefix
            backend:
              service:
                name: taiga-back
                port:
                  number: 8000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: taiga-back
                port:
                  number: 8000
          - path: /events/
            pathType: Prefix
            backend:
              service:
                name: taiga-events
                port:
                  number: 8888
