replicaCount: 1

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--http-enabled=true"
  - "--hostname=https://keycloak-taiga-team2.dedyn.io"
  - "--db=dev-file"
  - "--proxy=edge"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: VerySecret123
  - name: JAVA_OPTS_APPEND
    value: "-Xms256m -Xmx768m"
  - name: KC_HOSTNAME
    value: https://keycloak-taiga-team2.dedyn.io
  - name: KC_HOSTNAME_ADMIN_URL
    value: https://keycloak-taiga-team2.dedyn.io

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 1Gi

service:
  type: ClusterIP
  port: 8080

postgresql:
  enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port 443;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
      # Для WebSocket
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  rules:
    - host: keycloak-taiga-team2.dedyn.io
      paths:
        - path: /
          pathType: Prefix
  console:
    enabled: false
  tls:
    - secretName: keycloak-tls
      hosts:
        - keycloak-taiga-team2.dedyn.io