replicaCount: 1

keycloak:
  username: admin
  password: VerySecret123
  extraArgs:
    - start-dev
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 400m
      memory: 1Gi

  extraEnv:
    JAVA_OPTS_APPEND: "-Xms256m -Xmx768m"

service:
  type: NodePort
  port: 8080

postgresql:
  enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false" 
  hosts:
    - host: keycloak-taiga-team2.dedyn.io
      paths:
        - path: /
          pathType: Prefix
  tls: [] 

